apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "logging-pv"
spec:
  capacity:
    storage: "20Gi"
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: "ext4"
    volumeID: "vol-08e1654b32b16aedc"
